# Generated by Django 5.0.4 on 2024-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('deathday', models.DateTimeField()),
                ('placebirthday', models.CharField(max_length=255, null=True)),
                ('ptoho', models.ImageField(upload_to='media/%Y/%M/%D')),
                ('status', models.BooleanField(null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
            ],
        ),
    ]
